name       : gsound
version    : 1.0.2
release    : 6
source     :
    - https://download.gnome.org/sources/gsound/1.0/gsound-1.0.2.tar.xz : bba8ff30eea815037e53bee727bbd5f0b6a2e74d452a7711b819a7c444e78e53
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GSound is a small library for playing system sounds.
description: |
    GSound is a small library for playing system sounds.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
