name       : gsound
version    : 1.0.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gsound/1.0/gsound-1.0.1.tar.xz : ea0dd94429c0645f2f98824274ef04543fe459dd83a5449a68910acc3ba67f29
license    : LGPL-2.1
summary    : GSound is a small library for playing system sounds.
description: |
    GSound is a small library for playing system sounds.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
